version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:10.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run: ./node_modules/.bin/now dev &
      - run: yarn test:cy
